export const dataPointMapping: {[key: string]: string} = {
    SEQPLT: "Plant file sequence number",
    YEAR: "Data Year",
    PSTATABB: "Plant state abbreviation",
    PNAME: "Plant name",
    ORISPL: "DOE/EIA ORIS plant or facility code",
    OPRNAME: "Plant transmission or distribution system owner name",
    OPRCODE: "Plant transmission or distribution system owner ID",
    UTLSRVNM: "Utility name",
    UTLSRVID: "Utility ID",
    SECTOR: "Plant-level sector",
    FIPSCNTY: "Plant FIPS county code",
    CNTYNAME: "Plant county name",
    LAT: "Plant latitude",
    LON: "Plant longitude",
    NUMUNT: "Number of units",
    NUMGEN: "Number of generators",
    PLPRMFL: "Plant primary fuel",
    PLFUELCT: "Plant primary fuel category",
    PLNGENAN: "Plant annual net generation (MWh)",
    PLNOXAN: "Plant annual NOx emissions (tons)",
    PLNOXOZ: "Plant ozone season NOx emissions (tons)",
    PLGENACL: "Plant annual coal net generation (MWh)",
    PLGENAOL: "Plant annual oil net generation (MWh)",
    PLGENAGS: "Plant annual gas net generation (MWh)",
    PLGENANC: "Plant annual nuclear net generation (MWh)",
    PLGENAHY: "Plant annual hydro net generation (MWh)",
    PLGENABM: "Plant annual biomass net generation (MWh)",
    PLGENAWI: "Plant annual wind net generation (MWh)",
    PLGENASO: "Plant annual solar net generation (MWh)",
    PLGENAGT: "Plant annual geothermal net generation (MWh)",
    PLGENAOF: "Plant annual other fossil net generation (MWh)",
    PLGENAOP: "Plant annual other unknown/ purchased fuel net generation (MWh)",
    PLGENATN: "Plant annual total nonrenewables net generation (MWh)",
    PLGENATR: "Plant annual total renewables net generation (MWh)",
    PLGENATH: "Plant annual total nonhydro renewables net generation (MWh)",
    PLGENACY: "Plant annual total combustion net generation (MWh)",
    PLGENACN: "Plant annual total noncombustion net generation (MWh)",
    PLCLPR: "Plant coal generation percent (resource mix)",
    PLOLPR: "Plant oil generation percent (resource mix)",
    PLGSPR: "Plant gas generation percent (resource mix)",
    PLNCPR: "Plant nuclear generation percent (resource mix)",
    PLHYPR: "Plant hydro generation percent (resource mix)",
    PLBMPR: "Plant biomass generation percent (resource mix)",
    PLWIPR: "Plant wind generation percent (resource mix)",
    PLSOPR: "Plant solar generation percent (resource mix)",
    PLGTPR: "Plant geothermal generation percent (resource mix)",
    PLOFPR: "Plant other fossil generation percent (resource mix)",
    PLOPPR: "Plant other unknown / purchased fuel generation percent (resource mix)",
    PLTNPR: "Plant total nonrenewables generation percent (resource mix)",
    PLTRPR: "Plant total renewables generation percent (resource mix)",
    PLTHPR: "Plant total nonhydro renewables generation percent (resource mix)",
    PLCYPR: "Plant total combustion generation percent (resource mix)",
    PLCNPR: "Plant total noncombustion generation percent (resource mix)"
};
